Project:
  Name : Coolsmart
  RT_ID : 5156
  File : "测试.pdf"
InitSetting :
  - Name : ct
    Type : int
  - Name : has_a
    Type : int
Sample : 
  - Cmd : 3
    Offset : 7
    Len : 4
    Data : 
      - Name : 回风温度测量值
      - Name : 回风湿度测量值
      - Name : 送风温度测量值
      - Name : 环境温度测量值
      - Name : 排气压力
      - Name : 吸气压力
      - Name : 排气温度
      - Name : 吸气温度
      - Name : 机组运行状态
      - Name : 风机转速
      - Name : 压机转速
      - Name : 泵转速
      - Name : 泵进口压力
      - Name : 泵出口压力
      - Name : 泵扬程
      - Name : 冷凝器转速
      - Name : EEV开度
      - Name : 吸气过热度
      - Name : 排气过热度
      - Name : 制冷
      - Name : 加热
      - Name : 除湿加湿
      - Name : 节能卡温度1测量值
      - Name : 节能卡温度2测量值
      - Name : 节能卡温度3测量值
      - Name : 节能卡温度4测量值
      - Name : 节能卡温度5测量值
      - Name : 节能卡温度6测量值
      - Name : 节能卡温度7测量值
      - Name : 节能卡温度8测量值
      - Name : 节能卡温度9测量值
      - Name : 节能卡温度10测量值
      - Name : 节能卡温度11测量值
      - Name : 节能卡温度12测量值
      - Name : 节能卡温度13测量值
      - Name : 节能卡温度14测量值
      - Name : 节能卡温度15测量值
      - Name : 节能卡温度16测量值
      - Name : 风机运行状态
      - Name : 加湿器运行状态
      - Name : 加热器1运行时间
      - Name : 压缩机1运行时间
      - Name : 制冷泵1运行时间
      - Name : 送风温度设定点   
      - Name : 回风温度设定点
      - Name : 回风湿度设定点
      - Name : 监控开关机
      - Name : 监控波特率
      - Name :  监控地址
        Offset : 3
  - Cmd : 3
    Offset : 0x16E
    Len : 44
DataCode : |

Threshold :
  - Bool : True
    Level : 1
    SignalId : "0777001"
    SignalName : "状态告警"
    SignalDesc : "高压告警"
    Value : cData.alarm1&0x1
    SignalIndex : 1
  # - Bool : False
  #   Key : voltage
  #   Name : 电压
  #   Value : ((float)cData.r3_7[0])/100
RunCheckThresholdCode: |
    if ( 1 == 1) {
        }
Value :
  - Name : Ua
    Value : cData.r3_7[0]
  - Name : Ub
    Value : cData.r3_7[1]
AO :
  - SignalId : 1234567
    Desc : 测试1
  - SignalId : 1234568
    Desc : 测试2
DO :
  - SignalId : 1234567
    Desc : 测试3
  - SignalId : 1234568
    Desc : 测试4