Project:
  Name :  DCM3366PH241S
  RT_ID : 5156
  File : "DCM3366P—H2(1)-41S 型系列直流电表 Modbus-RTU 通信协议V1.03.pdf"
Sample : 
  - Cmd : 3
    Offset : 0x0000
    Len : 26
    Data : 
      - Name : "第 1 路电压"
        Unit : "V"
        Offset : 1
        Value: (($v[1]<<16)+$v[2])/1000
      - Name : "第 2 路电压"
        Unit : "V"
        Offset : 3
        Value: (($v[3]<<16)+$v[4])/1000
      - Name : "第 3 路电压"
        Unit : "V"
        Offset : 5
        Value: (($v[5]<<16)+$v[6])/1000
      - Name : "第 4 路电压"
        Unit : "V"
        Offset : 7
        Value: (($v[7]<<16)+$v[8])/1000
      - Name : "第 5 路电压"
        Unit : "V"
        Offset : 9
        Value: (($v[9]<<16)+$v[10])/1000
      - Name : "第 6 路电压"
        Unit : "V"
        Offset : 11
        Value: (($v[11]<<16)+$v[12])/1000
      - Name : "总电流"
        Unit : "A"
        Offset : 13
        Value: (($v[13]<<16)+$v[14])/10000
      - Name : "第 1 路电流"
        Unit : "A"
        Offset : 15
        Value: (($v[15]<<16)+$v[16])/10000
      - Name : "第 2 路电流"
        Unit : "A"
        Offset : 17
        Value: (($v[17]<<16)+$v[18])/10000
      - Name : "第 3 路电流"
        Unit : "A"
        Offset : 19
        Value: (($v[19]<<16)+$v[20])/10000
      - Name : "第 4 路电流"
        Unit : "A"
        Offset : 21
        Value: (($v[21]<<16)+$v[22])/10000
      - Name : "第 5 路电流"
        Unit : "A"
        Offset : 23
        Value: (($v[23]<<16)+$v[24])/10000
      - Name : "第 6 路电流"
        Unit : "A"
        Offset : 25
        Value: (($v[25]<<16)+$v[26])/10000

  - Cmd : 3
    Offset : 0x001a
    Len : 14
    Data : 
      - Name : "总功率"
        Unit : "kw"
        Offset : 1
        Value: (($v[1]<<16)+$v[2])/10000
      - Name : "第 1 路功率"
        Unit : "kw"
        Offset : 3
        Value: (($v[3]<<16)+$v[4])/10000
      - Name : "第 2 路功率"
        Unit : "kw"
        Offset : 5
        Value: (($v[5]<<16)+$v[6])/10000
      - Name : "第 3 路功率"
        Unit : "kw"
        Offset : 7
        Value: (($v[7]<<16)+$v[8])/10000
      - Name : "第 4 路功率"
        Unit : "kw"
        Offset : 9
        Value: (($v[9]<<16)+$v[10])/10000
      - Name : "第 5 路功率"
        Unit : "kw"
        Offset : 11
        Value: (($v[11]<<16)+$v[12])/10000
      - Name : "第 6 路功率"
        Unit : "kw"
        Offset : 13
        Value: (($v[13]<<16)+$v[14])/10000


  - Cmd : 3
    Offset : 0x0028
    Len : 14
    Data : 
      - Name : "总正向电能"
        Unit : "kWh"
        Offset : 41
        Value: (($v[1]<<16)+$v[2])/100
      - Name : "第 1 路正向电能"
        Unit : "kWh"
        Offset : 43
        Value: (($v[3]<<16)+$v[4])/100
      - Name : "第 2 路正向电能"
        Unit : "kWh"
        Offset : 45
        Value: (($v[5]<<16)+$v[6])/100
      - Name : "第 3 路正向电能"
        Unit : "kWh"
        Offset : 47
        Value: (($v[7]<<16)+$v[8])/100
      - Name : "第 4 路正向电能"
        Unit : "kWh"
        Offset : 49
        Value: (($v[9]<<16)+$v[10])/100
      - Name : "第 5 路正向电能"
        Unit : "kWh"
        Offset : 51
        Value: (($v[11]<<16)+$v[12])/100
      - Name : "第 6 路正向电能"
        Unit : "kWh"
        Offset : 53
        Value: (($v[13]<<16)+$v[14])/100


  - Cmd : 3
    Offset : 0x00a4
    Len : 2
    Data : 
      - Name : "DO1"
        Value : (($v[1]) & 0x1)
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合 
      - Name : "熔丝 1"
        Value : (($v[1]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 熔丝闭合
          - Key : 1
            Value : 熔丝断开 
      - Name : "熔丝 2"
        Value : (($v[1]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 熔丝闭合
          - Key : 1
            Value : 熔丝断开 
      - Name : "DI1"
        Value : (($v[1]>>3) & 0x1)
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合 
      - Name : "DI2"
        Value : (($v[1]>>4) & 0x1)
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : "1 路过压"
        Value : (($v[2]) & 0x1)
        AlertNormalValue : 0
      - Name : "2 路过压"
        Value : (($v[2]>>1) & 0x1)
        AlertNormalValue : 0
      - Name : "1 路欠压"
        Value : (($v[2]>>2) & 0x1)
        AlertNormalValue : 0
      - Name : "2 路欠压"
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
      - Name : "1 路过流"
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
      - Name : "2 路过流"
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
      - Name : "1 路熔丝"
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
      - Name : "2 路熔丝"
        Value : (($v[2]>>7) & 0x1)
        AlertNormalValue : 0
      - Name : "DI1"
        Value : (($v[2]>>8) & 0x1)
        AlertNormalValue : 0
      - Name : "DI2"
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
      - Name : "1 路过载"
        Value : (($v[2]>>10) & 0x1)
        AlertNormalValue : 0
      - Name : "2 路过载"
        Value : (($v[2]>>11) & 0x1)
        AlertNormalValue : 0




  - Cmd : 3
    Offset : 0x00a7
    Len : 24
    Data : 
      - Name : "第 1 路额定电压"
        Unit : "V"
        Offset : 1
        Value: (($v[1]<<16)+$v[2])/1000
      - Name : "第 2 路额定电压"
        Unit : "V"
        Offset : 3
        Value: (($v[3]<<16)+$v[4])/1000
      - Name : "第 3 路额定电压"
        Unit : "V"
        Offset : 5
        Value: (($v[5]<<16)+$v[6])/1000
      - Name : "第 4 路额定电压"
        Unit : "V"
        Offset : 7
        Value: (($v[7]<<16)+$v[8])/1000
      - Name : "第 5 路额定电压"
        Unit : "V"
        Offset : 9
        Value: (($v[9]<<16)+$v[10])/1000
      - Name : "第 6 路额定电压"
        Unit : "V"
        Offset : 11
        Value: (($v[11]<<16)+$v[12])/100
      - Name : "第 1 路标定电流"
        Unit : "A"
        Offset : 13
        Value: (($v[13]<<16)+$v[14])/100
      - Name : "第 2 路标定电流"
        Unit : "A"
        Offset : 15
        Value: (($v[15]<<16)+$v[16])/100
      - Name : "第 3 路标定电流"
        Unit : "A"
        Offset : 17
        Value: (($v[17]<<16)+$v[18])/100
      - Name : "第 4 路标定电流"
        Unit : "A"
        Offset : 19
        Value: (($v[19]<<16)+$v[20])/100
      - Name : "第 5 路标定电流"
        Unit : "A"
        Offset : 21
        Value: (($v[21]<<16)+$v[22])/100
      - Name : "第 6 路标定电流"
        Unit : "A"
        Offset : 23
        Value: (($v[23]<<16)+$v[24])/100




