Project:
  Name : EvoCyberMateDXModbus
  RT_ID : 5156
  File : "05130040-通信协议-A7-EVO-CyberMate-DX-modbus协议-中英文-2021-11-29  英维克.pdf"
Sample : 
  - Cmd : 3
    Offset : 0x0100
    Len : 66
    Data : 
      - Name : "1#回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 1
      - Name : "2#回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 2
      - Name : "3#回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 3
      - Name : "4#回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 4
      - Name : "5#回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 5
      - Name : "1#出风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 6
      - Name : "室外温度"
        Unit : "℃"
        Ratio : 10
        Offset : 9
      - Name : "1#回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 14
      - Name : "2#回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 15
      - Name : "3#回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 16
      - Name : "4#回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 17
      - Name : "5#回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 18
      - Name : "室外湿度"
        Unit : "%"
        Ratio : 10
        Offset : 19
      - Name : "出风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 20
      - Name : "回风压差"
        Unit : "Pa"
        Ratio : 10
        Offset : 21
      - Name : "加湿电流检测"
        Unit : "mA"
        Offset : 24
      - Name : "电压检测"
        Unit : "V"
        Offset : 25
      - Name : "IF液管出口温度"
        Unit : "℃"
        Ratio : 10
        Offset : 26
      - Name : "IF液管进口温度"
        Unit : "℃"
        Ratio : 10
        Offset : 27
      - Name : "1#系统高压"
        Unit : "Pa"
        Ratio : 10
        Offset : 28
      - Name : "2#系统高压"
        Unit : "Pa"
        Ratio : 10
        Offset : 29
      - Name : "1#系统低压"
        Unit : "Pa"
        Ratio : 10
        Offset : 30
      - Name : "2#系统低压"
        Unit : "Pa"
        Ratio : 10
        Offset : 31
      - Name : "1#系统液管温度"
        Unit : "℃"
        Ratio : 10
        Offset : 32
      - Name : "2#系统液管温度"
        Unit : "℃"
        Ratio : 10
        Offset : 33
      - Name : "1#吸气温度"
        Unit : "℃"
        Ratio : 10
        Offset : 34
      - Name : "2#吸气温度"
        Unit : "℃"
        Ratio : 10
        Offset : 35
      - Name : "1#系统排气温度"
        Unit : "℃"
        Ratio : 10
        Offset : 36
      - Name : "2#系统排气温度"
        Unit : "℃"
        Ratio : 10
        Offset : 37
      - Name : "IF泵出口温度"
        Unit : "℃"
        Ratio : 10
        Offset : 38
      - Name : "通道压差"
        Unit : "℃"
        Ratio : 10
        Offset : 40
      - Name : "1#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 43
      - Name : "2#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 44
      - Name : "3#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 45
      - Name : "4#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 46
      - Name : "5#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 47
      - Name : "6#外扩温度"
        Unit : "℃"
        Ratio : 10
        Offset : 48
      - Name : "1#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 61
      - Name : "2#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 62
      - Name : "3#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 63
      - Name : "4#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 64
      - Name : "5#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 65
      - Name : "6#外扩湿度"
        Unit : "%"
        Ratio : 10
        Offset : 66
  - Cmd : 3
    Offset : 0x0200
    Len : 28
    Data : 
      - Name : "内风机"
        Offset : 1
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "1#压缩机"
        Offset : 2
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "2#压缩机"
        Offset : 3
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "1#电加热"
        Offset : 4
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "2#电加热"
        Offset : 5
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "电极加湿"
        Offset : 7
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "1#外风机(壳管水阀)"
        Offset : 8
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "2#外风机(壳管水阀)"
        Offset : 9
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "IF室内电磁阀"
        Offset : 12
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "1#IF室外电磁阀"
        Offset : 13
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "2#IF室外电磁阀"
        Offset : 14
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "IF制冷泵"
        Offset : 15
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "红外加湿"
        Offset : 17
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "机组运行状态"
        Offset : 21
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "制冷状态"
        Offset : 26
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "加热状态"
        Offset : 27
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : "除湿状态"
        Offset : 28
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
  - Cmd : 3
    Offset : 0x0300
    Len : 8
    Data : 
      - Name : "温度设定点"
        Unit : ℃
        Ratio : 10
        Offset : 1
      - Name : "温度灵敏度"
        Unit : ℃
        Ratio : 10
        Offset : 2
      - Name : "湿度设定点"
        Unit : "%"
        Ratio : 10
        Offset : 3
      - Name : "温湿度灵敏度"
        Unit : "%"
        Ratio : 10
        Offset : 4
      - Name : "高温告警点"
        Unit : ℃
        Ratio : 10
        Offset : 5
      - Name : "低温告警点"
        Unit : ℃
        Ratio : 10
        Offset : 6
      - Name : "高湿告警点"
        Unit : ℃
        Ratio : 10
        Offset : 7
      - Name : "低湿告警点"
        Unit : ℃
        Ratio : 10
        Offset : 8
  - Cmd : 3
    Offset : 0x0400
    Len : 1
    Data : 
      - Name : "监控开关机"
        Offset : 1
        Options : 
          - Key : 0x15
            Value : 开机
          - Key : 0x17
            Value : 关机
  - Cmd : 3
    Offset : 0x500
    Len : 110
    Data :
      - Name : 回风高温告警
        Offset : 1
        AlertNormalValue : 0
      - Name : 回风低温告警
        Offset : 2
        AlertNormalValue : 0
      - Name : 回风高湿告警
        Offset : 3
        AlertNormalValue : 0
      - Name : 回风低湿告警
        Offset : 4
        AlertNormalValue : 0
      - Name : 1#回风温感故障
        Offset : 5
        AlertNormalValue : 0
      - Name : 1#出风温感故障
        Offset : 6
        AlertNormalValue : 0
      - Name : 回风湿感故障
        Offset : 11
        AlertNormalValue : 0
      - Name : 压差传感器故障
        Offset : 12
        AlertNormalValue : 0
      - Name : 气流丢失告警
        Offset : 23
        AlertNormalValue : 0
      - Name : 滤网堵塞告警
        Offset : 24
        AlertNormalValue : 0
      - Name : 电极加湿电流过小
        Offset : 27
        AlertNormalValue : 0
      - Name : 电极加湿电流过大
        Offset : 28
        AlertNormalValue : 0
      - Name : 电极加湿水位过高
        Offset : 29
        AlertNormalValue : 0
      - Name : 地板溢水
        Offset : 30
        AlertNormalValue : 0
      - Name : 电源电压过高
        Offset : 31
        AlertNormalValue : 0
      - Name : 电源电压过低
        Offset : 32
        AlertNormalValue : 0
      - Name : 电源缺相告警
        Offset : 33
        AlertNormalValue : 0
      - Name : 电源逆相告警
        Offset : 33
        AlertNormalValue : 0
      - Name : 电源频率异常
        Offset : 35
        AlertNormalValue : 0
      - Name : 1#系统高压
        Offset : 42
        AlertNormalValue : 0
      - Name : 1#系统低压
        Offset : 43
        AlertNormalValue : 0
      - Name : 2#系统高压
        Offset : 44
        AlertNormalValue : 0
      - Name : 2#系统低压
        Offset : 45
        AlertNormalValue : 0
      - Name : 1#系统高压锁定
        Offset : 46
        AlertNormalValue : 0
      - Name : 2#系统高压锁定
        Offset : 47
        AlertNormalValue : 0
      - Name : 1#系统低压锁定
        Offset : 48
        AlertNormalValue : 0
      - Name : 2#系统低压锁定
        Offset : 49
        AlertNormalValue : 0
      - Name : 1#系统排气温度保护
        Offset : 50
        AlertNormalValue : 0
      - Name : 2#系统排气温度保护
        Offset : 51
        AlertNormalValue : 0
      - Name : 1#系统排气温度锁定
        Offset : 52
        AlertNormalValue : 0
      - Name : 2#系统排气温度锁定
        Offset : 53
        AlertNormalValue : 0
      - Name : 1#盘管防冻保护
        Offset : 54
        AlertNormalValue : 0
      - Name : 2#盘管防冻保护
        Offset : 55
        AlertNormalValue : 0
      - Name : 1#制冷系统异常
        Offset : 56
        AlertNormalValue : 0
      - Name : 2#制冷系统异常
        Offset : 57
        AlertNormalValue : 0
      - Name : 1#系统短周期报警
        Offset : 58
        AlertNormalValue : 0
      - Name : 2#系统短周期报警
        Offset : 59
        AlertNormalValue : 0
      - Name : 1#系统冷凝单元变频驱动板故障
        Offset : 60
        AlertNormalValue : 0
      - Name : 2#系统冷凝单元变频驱动板故障
        Offset : 61
        AlertNormalValue : 0
      - Name : 内风机故障
        Offset : 65
        AlertNormalValue : 0
      - Name : 红外加湿水盘过温保护
        Offset : 66
        AlertNormalValue : 0
      - Name : 红外加湿高水位
        Offset : 67
        AlertNormalValue : 0
      - Name : 红外加湿缺水
        Offset : 68
        AlertNormalValue : 0
      - Name : 1#冷凝温感失效
        Offset : 76
        AlertNormalValue : 0
      - Name : 2#冷凝温感失效
        Offset : 77
        AlertNormalValue : 0
      - Name : 1#吸气温感失效
        Offset : 78
        AlertNormalValue : 0
      - Name : 2#吸气温感失效
        Offset : 79
        AlertNormalValue : 0
      - Name : 1#排气温感失效
        Offset : 80
        AlertNormalValue : 0
      - Name : 2#排气温感失效
        Offset : 81
        AlertNormalValue : 0
      - Name : 1#低压传感器失效
        Offset : 82
        AlertNormalValue : 0
      - Name : 2#低压传感器失效
        Offset : 83
        AlertNormalValue : 0
      - Name : 1#冷凝压力传感器失效
        Offset : 84
        AlertNormalValue : 0
      - Name : 2#冷凝压力传感器失效
        Offset : 85
        alertNormalValue : 0
      - Name : 1#室外变频器通信故障
        Offset : 86
        AlertNormalValue : 0
      - Name : 2#室外变频器通信故障
        Offset : 87
        AlertNormalValue : 0
      - Name : 泵循环流量丢失
        Offset : 88
        AlertNormalValue : 0
      - Name : 室外温度传感器失效
        Offset : 89
        AlertNormalValue : 0
      - Name : 泵循环液管温感失效
        Offset : 90
        AlertNormalValue : 0
      - Name : 泵柜过电压告警
        Offset : 91
        AlertNormalValue : 0
      - Name : 泵柜欠电压告警
        Offset : 92
        AlertNormalValue : 0
      - Name : 泵柜缺相告警
        Offset : 93
        AlertNormalValue : 0
      - Name : 泵柜逆相告警
        Offset : 94
        AlertNormalValue : 0
      - Name : 泵柜低液位告警
        Offset : 95
        AlertNormalValue : 0
      - Name : 泵柜通信故障
        Offset : 96
        AlertNormalValue : 0
      - Name : 1#低过热度保护
        Offset : 97
        AlertNormalValue : 0
      - Name : 2#低过热度保护
        Offset : 98
        AlertNormalValue : 0
      - Name : 通道压差传感器故障告警
        Offset : 110
        AlertNormalValue : 0
  - Cmd : 3
    Offset : 0x058C
    Len : 5
    Data :
      - Name : 1#变频器故障锁定
        Offset : 1
        AlertNormalValue : 0
      - Name : 2#变频器故障锁定
        Offset : 2
        AlertNormalValue : 0
      - Name : 电加热系统故障
        Offset : 3
        AlertNormalValue : 0
      - Name : 1#排气过热度过高
        Offset : 4
        AlertNormalValue : 0
      - Name : 2#排气过热度过高
        Offset : 5
        AlertNormalValue : 0
SET_RET_CODE : |
  case AC_Control_Code::AC_START: {
        if(tab_reg[0] == 1) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      }
      case AC_Control_Code::AC_STOP: {
        if(tab_reg[0] == 0) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      } 
      case AC_Control_Code::AC_SET_TEMPERATURE:
      case AC_Control_Code::AC_SET_HUMID: {
        if(tab_reg[0] == last_data_) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      }
      
SET_DO_CODE : |
  if(setting["signal_id"].asString() != "") {
      if(setting["signal_id"].asString() == "140800280010") {
          //开机
          state = AC_Control_Code::AC_START;
          cmd_result_ = -1;
          last_data_ = 1;
          modbus_write_register(0x400, 0x15);
          if((uint32_t)outBufferSize >= sizeof(int)) {
              *((int*)outBuffer) = 1;//通知取状态
              bytesReturned = sizeof(int);
          }
      }else if(setting["signal_id"].asString() == "140800300010") {
          //关机
          state = AC_Control_Code::AC_STOP;
          cmd_result_ = -1;
          last_data_ = 0;
          modbus_write_register(0x400, 0x17);
          if((uint32_t)outBufferSize >= sizeof(int)) {
              *((int*)outBuffer) = 1;//通知取状态
              bytesReturned = sizeof(int);
          }
      }
  }

SET_AO_CODE: |
  if(setting["signal_id"].asString() == "150800310010") {
      if(setting["SetValue"] != Json::nullValue && setting["SetValue"].type()  != Json::nullValue) {
          int16_t newValue = atoi(setting["SetValue"].asString().c_str())*10;
          //送风温度
          state = AC_Control_Code::AC_SET_TEMPERATURE;
          cmd_result_ = -1;
          OpenPort();
          modbus_write_register(0x300, newValue);
          if((uint32_t)outBufferSize >= sizeof(int)) {
              *((int*)outBuffer) = 1;//通知取状态
              bytesReturned = sizeof(int);
          }                       
      }
  }else if(setting["signal_id"].asString() == "150800340010") {
      if(setting["SetValue"] != Json::nullValue && setting["SetValue"].type()  != Json::nullValue) {
          int16_t newValue = atoi(setting["SetValue"].asString().c_str())*10;
          //湿度
          state = AC_Control_Code::AC_SET_HUMID;
          cmd_result_ = -1;
          OpenPort();
          modbus_write_register(0x302, newValue);
          if((uint32_t)outBufferSize >= sizeof(int)) {
              *((int*)outBuffer) = 1;//通知取状态
              bytesReturned = sizeof(int);
          }                       
      }
  }