Project:
  Name : HaiWu
  RT_ID : 5156
  File : "海悟MODBUS通讯协议(风/水冷定频机房空调)"
Sample : 
  - Cmd : 1
    Offset : 8001
    Len : 32
    Data : 
      - Name : "开/关状态"
        Offset : 1
        Options : 
          - Key : 0
            Value : 关机
          - Key : 1
            Value : 开机 
      - Name : "远程开关"
        Offset : 10
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 开启 
      - Name : "机械/节能制冷"
        Offset : 12
        Options : 
          - Key : 0
            Value : 机械制冷
          - Key : 1
            Value : 节能制冷 
      - Name : "电源故障（过/欠压）"
        Offset : 17
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "相序错误"
        Offset : 18
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "缺相错误"
        Offset : 19
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "电加热保护"
        Offset : 20
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "加湿器报警"
        Offset : 21
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "烟雾报警"
        Offset : 22
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "水浸报警"
        Offset : 23
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "湿膜低水位报警"
        Offset : 24
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "湿膜水位开关故障"
        Offset : 25
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "EEPROM故障"
        Offset : 26
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "本地联网通讯故障"
        Offset : 29
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "扩展板通讯故障"
        Offset : 30
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "状态远程内温探头故障"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "滤网堵塞报警"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 1
    Offset : 8033
    Len : 8
    Data :   
      - Name : "风机1转速反馈故障"
        Offset : 1
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机2转速反馈故障"
        Offset : 2
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机3转速反馈故障"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机4转速反馈故障"
        Offset : 4
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机5转速反馈故障"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机6转速反馈故障"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机7转速反馈故障"
        Offset : 7
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机8转速反馈故障"
        Offset : 8
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 1
    Offset : 8041
    Len : 8
    Data :   
      - Name : "风机过载故障"
        Offset : 1
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "气流丢失故障"
        Offset : 2
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "高温报警"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "低温报警"
        Offset : 4
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "高湿报警"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "低湿报警"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风高温报警"
        Offset : 7
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风低温报警"
        Offset : 8
        AlertNormalValue : 0
        TeleSignalId : 12018
  - Cmd : 1
    Offset : 8049
    Len : 3
    Data :   
      - Name : "回风温度探头1故障"
        Offset : 1
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "回风温度探头2故障"
        Offset : 2
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "回风温度探头3故障"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 1
    Offset : 8052
    Len : 4
    Data :   
      - Name : "回风湿度探头故障"
        Offset : 1
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风温度1探头故障"
        Offset : 2
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风温度2探头故障"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风温度3探头故障"
        Offset : 4
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 1
    Offset : 8056
    Len : 40
    Data : 
      - Name : "送风湿度探头故障"
        Offset : 1
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机电流探头故障"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "电量检测故障"
        Offset : 7
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机欠流"
        Offset : 8
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "外风机脏堵"
        Offset : 9
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1高压保护"
        Offset : 10
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1低压保护"
        Offset : 11
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "高压开关1故障"
        Offset : 12
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "低压开关1故障"
        Offset : 13
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "吸气温度1探头故障"
        Offset : 14
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "排气温度1探头故障"
        Offset : 15
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1蒸发温度过低"
        Offset : 16
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1排气高温"
        Offset : 17
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压缩机1过流"
        Offset : 18
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压缩机1欠流"
        Offset : 19
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1吸气压力传感器故障"
        Offset : 20
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "液管温度1探头故障"
        Offset : 21
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统1吸气高温锁定"
        Offset : 22
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压缩机1 "
        Offset : 24
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 开启 
      - Name : "系统2高压保护"
        Offset : 26
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统2低压保护"
        Offset : 27
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "高压开关2故障"
        Offset : 28
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "低压开关2故障"
        Offset : 29
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "吸气温度2探头故障"
        Offset : 30
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "排气温度2探头故障"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统2蒸发温度过低"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统2排气高温"
        Offset : 33
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统2吸气压力传感器故障"
        Offset : 36
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "液管温度2探头故障"
        Offset : 37
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统2吸气高温"
        Offset : 38
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压缩机2"
        Offset : 40
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 开启 


  - Cmd : 3
    Offset : 8001
    Len : 27
    Data : 
      - Name : "系统运行模式-停机"
        Value : ( ($v[1]&0x1) == 0 )
        CValue : ( (pData[0]&0x1) == 0 )
      - Name : "系统运行模式-制冷"
        Value : (($v[1]>>4) & 0x1)
        CValue : ((pData[0]>>4) & 0x1)
      - Name : "系统运行模式-制热"
        Value : (($v[1]>>1) & 0x1)
        CValue : ((pData[0]>>1) & 0x1)
      - Name : "系统运行模式-加湿"
        Value : (($v[1]>>2) & 0x1)
        CValue : ((pData[0]>>2) & 0x1)
      - Name : "系统运行模式-除湿"
        Value : (($v[1]>>3) & 0x1)
        CValue : ((pData[0]>>3) & 0x1)
      - Name : "系统运行模式-待机"
        Value : (($v[1]>>4) & 0x1)
        CValue : ((pData[0]>>4) & 0x1)
      - Name : "系统运行模式-故障停机"
        Value : (($v[1]>>5) & 0x1)
        CValue : ((pData[0]>>5) & 0x1)
      - Name : "系统运行模式-手动关机"
        Value : (($v[1]>>6) & 0x1)
        CValue : ((pData[0]>>6) & 0x1)
      - Name : "系统运行模式-主/备"
        Value : (($v[1]>>7) & 0x1)
        CValue : ((pData[0]>>7) & 0x1)
      - Name : "系统运行模式-断网"
        Value : (($v[1]>>8) & 0x1)
        CValue : ((pData[0]>>8) & 0x1)
      - Name : "系统运行模式-干接点关机"
        Value : (($v[1]>>9) & 0x1)
        CValue : ((pData[0]>>9) & 0x1)
      - Name : "烟雾报警"
        Offset : 2
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "送风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 3
      - Name : "室内温度"
        Unit : "℃"
        Ratio : 10
        Offset : 4
      - Name : "回风温度"
        Unit : "℃"
        Ratio : 10
        Offset : 5
      - Name : "回风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 6
      - Name : "机组累计运行时间"
        Unit : "小时"
        Offset : 7
      - Name : "电源电压"
        Unit : "V"
        Offset : 14
      - Name : "送风湿度"
        Unit : "%"
        Ratio : 10
        Offset : 15
      - Name : "计算温度"
        Unit : "℃"
        Ratio : 10
        Offset : 25
      - Name : "计算湿度"
        Unit : "%"
        Ratio : 10
        Offset : 26
      - Name : "内风机风速"
        Offset : 27
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 开启

  - Cmd : 1
    Offset : 8102
    Len : 31
    Data : 
      - Name : "水流开关"
        Offset : 1
        Options : 
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 开启
      - Name : "外风机变频驱动通讯故障"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "室外温度传感器故障"
        Offset : 4
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压力传感器故障"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统高压保护"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统低压保护"
        Offset : 7
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "外风机变频驱动故障"
        Offset : 11
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机过热保护"
        Offset : 12
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "与室内机通讯故障"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 3
    Offset : 8101
    Len : 6
    Data : 
      - Name : "出水水温"
        Unit : "℃"
        Ratio : 10
        Offset : 1
      - Name : "外风机转速"
        Unit : "Hz"
        Ratio : 10
        Offset : 2
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 开启
      - Name : "室外温度"
        Unit : "℃"
        Ratio : 10
        Offset : 3
      - Name : "回水水温"
        Unit : "℃"
        Ratio : 10
        Offset : 4
      - Name : "比例水阀开度"
        Unit : "%"
        Offset : 6
  - Cmd : 1
    Offset : 8134
    Len : 31
    Data : 
      - Name : "水流开关"
        Offset : 1
        Options : 
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 开启
      - Name : "外风机变频驱动通讯故障"
        Offset : 3
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "室外温度传感器故障"
        Offset : 4
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "压力传感器故障"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统高压保护"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "系统低压保护"
        Offset : 7
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "外风机变频驱动故障"
        Offset : 11
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "风机过热保护"
        Offset : 12
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "与室内机通讯故障"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12018
  - Cmd : 3
    Offset : 8109
    Len : 6
    Data : 
      - Name : "出水水温"
        Unit : "℃"
        Ratio : 10
        Offset : 1
      - Name : "外风机转速"
        Unit : "HZ"
        Offset : 2
        Options : 
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 开启
      - Name : "室外温度"
        Unit : "℃"
        Ratio : 10
        Offset : 3
      - Name : "回水水温"
        Unit : "℃"
        Ratio : 10
        Offset : 4
      - Name : "比例水阀开度"
        Unit : "%"
        Offset : 6

  - Cmd : 1
    Offset : 8201
    Len : 32
    Data : 
      - Name : "氟泵"
        Offset : 1
        Options : 
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 开启
      - Name : "氟泵高扬程锁定告警"
        Offset : 14
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵低扬程锁定告警"
        Offset : 15
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵进口压力传感器故障"
        Offset : 19
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵出口压力传感器故障"
        Offset : 20
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "相序错误"
        Offset : 21
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "泵柜环温传感器故障报警"
        Offset : 25
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "泵柜驱动故障报警"
        Offset : 27
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵驱动通讯故障"
        Offset : 28
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵过温锁定告警"
        Offset : 29
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "与室内机通讯故障"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12018

  - Cmd : 1
    Offset :  8233
    Len : 32
    Data : 
      - Name : "氟泵"
        Offset : 1
        Options : 
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 开启
      - Name : "氟泵高扬程锁定告警"
        Offset : 14
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵低扬程锁定告警"
        Offset : 15
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵进口压力传感器故障"
        Offset : 19
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵出口压力传感器故障"
        Offset : 20
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "相序错误"
        Offset : 21
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "泵柜环温传感器故障报警"
        Offset : 25
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "泵柜驱动故障报警"
        Offset : 27
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵驱动通讯故障"
        Offset : 28
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "氟泵过温锁定告警"
        Offset : 29
        AlertNormalValue : 0
        TeleSignalId : 12018
      - Name : "与室内机通讯故障"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12018
  - Cmd : 3
    Offset : 3501
    Len : 12
    Data :
      - Name : "回风温度设定值"
        Unit : "℃"
        Ratio : 10
        Offset : 1
      - Name : "出风温度设定值"
        Unit : "℃"
        Ratio : 10
        Offset : 2
      - Name : "远程温度设定值"
        Unit : "℃"
        Ratio : 10
        Offset : 3
      - Name : "设定湿度"
        Unit : "%"
        Ratio : 10
        Offset : 4
      - Name : "高温报警"
        Unit : "℃"
        Ratio : 10
        Offset : 5
      - Name : "低温报警"
        Unit : "℃"
        Ratio : 10
        Offset : 6
      - Name : "高湿报警"
        Unit : "%"
        Ratio : 10
        Offset : 7
      - Name : "低湿报警"
        Unit : "%"
        Ratio : 10
        Offset : 8
      - Name : "开/关机"
        Offset : 9
        Options : 
          - Key : 0
            Value : 关机
          - Key : 1
            Value : 开机
      - Name : "本地操作"
        Offset : 10
        Options : 
          - Key : 0
            Value : 允许
          - Key : 1
            Value : 禁止
      - Name : "启动延时"
        Offset : 12
        Unit : "秒"
SET_RET_CODE : |
  case AC_Control_Code::AC_START: {
        if(tab_reg[0] == last_data_) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      }
      case AC_Control_Code::AC_STOP: {
        if(tab_reg[0] == last_data_) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      } 
      case AC_Control_Code::AC_SET_TEMPERATURE:
      case AC_Control_Code::AC_SET_HUMID: {
        if(tab_reg[0] == last_data_) {
            cmd_result_ = 1;
        } else {
            cmd_result_ = 3;
        }
        Reset();
        return false;
      }
      
SET_DO_CODE : |
  if(setting["signal_id"].asString() != "") {
      if(setting["signal_id"].asString() == "140800280010") {
          //开机
          state = AC_Control_Code::AC_START;
          cmd_result_ = -1;
          last_data_ = 1;
          modbus_write_register(3509, 1);
          return 0;
      }else if(setting["signal_id"].asString() == "140800300010") {
          //关机
          state = AC_Control_Code::AC_STOP;
          cmd_result_ = -1;
          last_data_ = 0;
          modbus_write_register(3509, 0);
          return 0;
      }
  }

SET_AO_CODE: |
  if(setting["signal_id"].asString() == "150800310010") {
      if(setting["SetValue"] != Json::nullValue && setting["SetValue"].type()  != Json::nullValue) {
          int16_t newValue = atoi(setting["SetValue"].asString().c_str())*10;
          //送风温度
          state = AC_Control_Code::AC_SET_TEMPERATURE;
          cmd_result_ = -1;
          last_data_ = newValue;
          modbus_write_register(3501, newValue);
          return 0;                    
      }
  }else if(setting["signal_id"].asString() == "150800340010") {
      if(setting["SetValue"] != Json::nullValue && setting["SetValue"].type()  != Json::nullValue) {
          int16_t newValue = atoi(setting["SetValue"].asString().c_str())*10;
          //湿度
          state = AC_Control_Code::AC_SET_HUMID;
          cmd_result_ = -1;
          last_data_ = newValue;
          modbus_write_register(3504, newValue);
          return 0;                       
      }
  }
