Project:
  Name : HuaYiZFSL
  RT_ID : 5156
  File : "开发区联通换热485通讯地址0619(华奕）.xls"
Sample : 
  - Cmd : 3
    Offset : 0
    Len : 28
    Data : 
      - Name : 机组手动运行/自动启动
        Offset : 1
        Options :
          - Key : 0
            Value : 手动
          - Key : 1
            Value : 自动
      - Name : 远程/本地
        Offset : 3
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 机组状态
        Offset : 4
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵1报警
        Offset : 5
        AlertNormalValue : 0
      - Name : 水泵2报警
        Offset : 6
        AlertNormalValue : 0
      - Name : 水泵3报警
        Offset : 7
        AlertNormalValue : 0
      - Name : 水泵4报警
        Offset : 8
        AlertNormalValue : 0
      - Name : 水泵5报警
        Offset : 9
        AlertNormalValue : 0
      - Name : 潜水泵1报警
        Offset : 10
        AlertNormalValue : 0
      - Name : 潜水泵2报警
        Offset : 11
        AlertNormalValue : 0
      - Name : 机组状态2
        Offset : 12
        AlertNormalValue : 0
      - Name : 立管1高限报警
        Offset : 13
        AlertNormalValue : 0
      - Name : 立管2高限报警
        Offset : 14
        AlertNormalValue : 0
      - Name : 立管低限告警报警
        Offset : 15
        AlertNormalValue : 0
      - Name : 消防联动
        Offset : 16
        AlertNormalValue : 0
      - Name : 水浸检测
        Offset : 17
        AlertNormalValue : 0
      - Name : 水泵1运行状态
        Offset : 18
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵2运行状态
        Offset : 19
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵3运行状态
        Offset : 20
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵4运行状态
        Offset : 21
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵5运行状态
        Offset : 22
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 潜水泵1运行状态
        Offset : 23
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 潜水泵2运行状态
        Offset : 24
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 排水阀运行状态
        Offset : 25
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 补水阀运行状态
        Offset : 26
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 大水箱高液位
        Offset : 27
        AlertNormalValue : 0
      - Name : 大水箱高液位
        Offset : 28
        AlertNormalValue : 0
  - Cmd : 3
    Offset : 45
    Len : 44
    Type : "f"
    Data : 
      - Name : 水泵1启动值
        Offset : 1
      - Name : 水泵2启动值
        Offset : 2
      - Name : 水泵3启动值
        Offset : 3
      - Name : 水泵4启动值
        Offset : 4
      - Name : 水泵5启动值
        Offset : 5
      - Name : 风机1转速反馈
        Offset : 6
      - Name : 风机2转速反馈
        Offset : 7
      - Name : 风机3转速反馈
        Offset : 8
      - Name : 风机4转速反馈
        Offset : 9
      - Name : 风机5转速反馈
        Offset : 10
      - Name : 电动阀1反馈
        Offset : 11
      - Name : 电动阀2反馈
        Offset : 12
      - Name : 电动阀3反馈
        Offset : 13
      - Name : 电动阀4反馈
        Offset : 14
      - Name : 电动阀5反馈
        Offset : 15
      - Name : 室外温度
        Offset : 16
      - Name : 室外湿度
        Offset : 17
      - Name : 湿球温度
        Offset : 18
      - Name : 温度启动上限
        Offset : 19
      - Name : 温度启动下限
        Offset : 20
      - Name : 液位启动上限
        Offset : 21
      - Name : 液位启动下限
        Offset : 22
      - Name : 水箱液位
        Offset : 22