Project:
  Name : ITeaqSBMS
  RT_ID : 5156
  File : "电池监控仪SBMS系列后台协议V203.pdf"
BlockTemplate :
  GroupAlert :
    BlockLength : 16
    BlockType : 'C'
    BlockContent :
      - Name : "第%s组电池组总电压-过压告警"
        Value : ($v[1] & 0x1)
        CValue : (pData[0] & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-欠压告警"
        Value : (($v[1]>>1) & 0x1)
        CValue : ((pData[0]>>1) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-充电电流异常"
        Value : (($v[1]>>2) & 0x1)
        CValue : ((pData[0]>>2) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-放电电流异常"
        Value : (($v[1]>>3) & 0x1)
        CValue : ((pData[0]>>3) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-电池开关断开"
        Value : (($v[1]>>4) & 0x1)
        CValue : ((pData[0]>>4) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-电流板通讯故障"
        Value : (($v[1]>>5) & 0x1)
        CValue : ((pData[0]>>5) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s组电池组总电压-电池组容量低"
        Value : (($v[1]>>6) & 0x1)
        CValue : ((pData[0]>>6) & 0x1)
        AlertNormalValue : 0
  BatteryAlarm :
    BlockLength : 2
    BlockType : 'S'
    BlockContent :
      - Name : "第%s号电池电池-电压超上限"
        Value : ($v[1] & 0x1)
        CValue : (pData[0] & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-电压超下限"
        Value : (($v[1]>>1) & 0x1)
        CValue : ((pData[0]>>1) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-内阻超限"
        Value : (($v[1]>>2) & 0x1)
        CValue : ((pData[0]>>2) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-温度超上限"
        Value : (($v[1]>>3) & 0x1)
        CValue : ((pData[0]>>3) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-电阻差异超上限"
        Value : (($v[1]>>4) & 0x1)
        CValue : ((pData[0]>>4) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-VBUS模块通讯故障"
        Value : (($v[1]>>5) & 0x1)
        CValue : ((pData[0]>>5) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-电压差异超限"
        Value : (($v[1]>>7) & 0x1)
        CValue : ((pData[0]>>7) & 0x1)
        AlertNormalValue : 0
      - Name : "第%s号电池电池-温度差异超限"
        Value : (($v[1]>>10) & 0x1)
        CValue : ((pData[0]>>10) & 0x1)
        AlertNormalValue : 0
        
Sample : 
  - Cmd : 3
    Offset : 1000
    Len : 8
    Data : 
      - Name : "第1组电池组总电压"
        Ratio : 10
        Unit : "V"
      - Name : "第2组电池组总电压"
        Ratio : 10
        Unit : "V"
      - Name : "第3组电池组总电压"
        Ratio : 10
        Unit : "V"
      - Name : "第4组电池组总电压"
        Ratio : 10
        Unit : "V"
      - Name : "第1组电池组总电流"
        Ratio : 10
        Unit : "A"
      - Name : "第2组电池组总电流"
        Ratio : 10
        Unit : "A"
      - Name : "第3组电池组总电流"
        Ratio : 10
        Unit : "A"
      - Name : "第4组电池组总电流"
        Ratio : 10
        Unit : "A"
  - Cmd : 3
    Offset : 1008
    Len : 4
    Transform : "bits"
    Data :
      - ArrayBlock : GroupAlert
        ArrayStart : 1
        ArrayEnd : 4
  - Cmd : 3
    Offset : 1012
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的电压"
        ArrayStart : 0
        ArrayLength : 125
        Offset : 0
        Unit : "V"
        Ratio : 1000
  - Cmd : 3
    Offset : 1127
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的电压"
        ArrayStart : 125
        ArrayLength : 125
        Offset : 0
        Unit : "V"
        Ratio : 1000
  - Cmd : 3
    Offset : 1262
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的温度"
        ArrayStart : 0
        ArrayLength : 125
        Offset : 0
        Unit : "℃"
        Ratio : 10
  - Cmd : 3
    Offset : 1387
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的温度"
        ArrayStart : 125
        ArrayLength : 125
        Offset : 0
        Unit : "℃"
        Ratio : 10
  - Cmd : 3
    Offset : 1512
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的内阻"
        ArrayStart : 0
        ArrayLength : 125
        Offset : 0
        Unit : "mΩ"
        Ratio : 1000
  - Cmd : 3
    Offset : 1627
    Len : 125
    Data : 
      - ArrayName : "第%d号电池的内阻"
        ArrayStart : 125
        ArrayLength : 125
        Offset : 0
        Unit : "mΩ"
        Ratio : 1000
  - Cmd : 3
    Offset : 1762
    Len : 125
    Data : 
      - ArrayBlock : BatteryAlarm
        ArrayStart : 1
        ArrayEnd : 125
  - Cmd : 3
    Offset : 1887
    Len : 125
    Data : 
      - ArrayBlock : BatteryAlarm
        ArrayStart : 126
        ArrayEnd : 250