Project:
  Name :  JBF293K
  RT_ID : 5156
  File : "JBF293K 接口卡 RS232/485 通讯协议 V1.4"
Sample : 
  - Cmd : 3
    Offset : 0x0020
    Len : 1
    Data : 
      - Name : "控制器心跳"
      - Name : "控制器正常"
      - Name : "控制器故障"
      - Name : "控制器复位"
      - Name : "控制器消音"
      - Name : "火警"
      - Name : "故障"
      - Name : "故障恢复"
      - Name : "回路故障"
      - Name : "回路故障恢复"
      - Name : "自动启动"
      - Name : "自动停止"
      - Name : "手动启动"
      - Name : "手动停止"
      - Name : "设备回答"
      - Name : "回答撤销"
      - Name : "部件隔离"
      - Name : "部件隔离撤销"
      - Name : "多线手动启动"
      - Name : "多线手动停止"
      - Name : "多线回答"
      - Name : "多线停止回答"
      - Name : "多线自动启动"
      - Name : "多线自动停止"
      - Name : "多线自动启动延时"
      - Name : "多线应答缺失"
      - Name : "多线线路故障"
      - Name : "多线线路故障恢复"
      - Name : "模拟报警"
      - Name : "监管报警"
      - Name : "监管报警撤销"
      - Name : "气体线路故障"
      - Name : "气体线路故障恢复"
      - Name : "气体喷洒应答"
      - Name : "气体喷洒应答撤销"
      - Name : "声光启动"
      - Name : "声光停止"
      - Name : "相关设备动作"
      - Name : "相关设备动作停止"
      - Name : "防火区启动"
      - Name : "防火区停止"
      - Name : "喷洒启动"
      - Name : "延时启动"
      - Name : "远程停止动作撤销"
      - Name : "板故障"
      - Name : "板故障恢复"
      - Name : "主电故障"
      - Name : "主电故障恢复"
      - Name : "备电故障"
      - Name : "备电故障恢复"
      - Name : "防火门相关命令"
      - Name : "电气火灾相关命令"
      - Name : "消防电源监控主机"
      - Name : "单常开防火门"
      - Name : "单常闭防火门"
      - Name : "双常开防火门"
      - Name : "双常闭防火门"
      - Name : "防火门故障"
      - Name : "防火门故障撤销"
      - Name : "防火门延时关闭"
      - Name : "防火门正在关闭（自动）"
      - Name : "防火门正在关闭消息撤销(自动)"
      - Name : "防火门正在关闭(手动)"
      - Name : "防火门正在关闭消息撤销(手动)"
      - Name : "防火门成功关闭(由于启动)"
      - Name : "防火门成功关闭消息撤销"
      - Name : "防火门屏蔽"
      - Name : "防火门屏蔽撤销"
      - Name : "全部探测器"
      - Name : "剩余电流探测器"
      - Name : "温度探测器"
      - Name : "故障电弧探测器"
      - Name : "过电流探测器"
      - Name : "脱扣继电器"
      - Name : "电气火灾探测器报警"
      - Name : "电气火灾探测器故障"
      - Name : "电气火灾探测器故障撤销"
      - Name : "电气火灾探测器脱扣动作(自动)"
      - Name : "电气火灾探测器脱扣停止(自动)"
      - Name : "电气火灾探测器脱扣动作(手动)"
      - Name : "电气火灾探测器脱扣停止(手动)"
      - Name : "电气火灾探测器屏蔽"
      - Name : "电气火灾探测器屏蔽撤销"
      - Name : "电压模块"
      - Name : "电压/电流模块"
      - Name : "电流模块"
      - Name : "故障"
      - Name : "故障恢复"
      - Name : "欠压故障"
      - Name : "过压故障"
      - Name : "缺相故障"
      - Name : "过载故障"
      - Name : "错相故障"
      - Name : "通道供电中断故障"
      - Name : "供电中断故障"
      - Name : "输入动作"
      - Name : "输入撤销"
      - Name : "输出动作"
      - Name : "输出撤销"
      - Name : "屏蔽"
      - Name : "屏蔽撤销"
      - Name : "故障恢复"