Project:
  Name : JZLKD
  RT_ID : 5156
  File : "空开二极管开关量板.xls"
Sample :
  - Cmd : 3
    Offset : 1
    Len : 1
    Data :
      - Name : "输入8"
        Value : '(($v[1] >> 15) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 15) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入7"
        Value : '(($v[1] >> 14) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 14) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入6"
        Value : '(($v[1] >> 13) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 13) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入5"
        Value : '(($v[1] >> 12) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 12) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入4"
        Value : '(($v[1] >> 11) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 11) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入3"
        Value : '(($v[1] >> 10) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 10) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入2"
        Value : '(($v[1] >> 9) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 9) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输入1"
        Value : '(($v[1] >> 8) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 8) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出8"
        Value : '(($v[1] >> 7) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 7) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出7"
        Value : '(($v[1] >> 6) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 6) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出6"
        Value : '(($v[1] >> 5) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 5) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出5"
        Value : '(($v[1] >> 4) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 4) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出4"
        Value : '(($v[1] >> 3) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 3) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出3"
        Value : '(($v[1] >> 2) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 2) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出2"
        Value : '(($v[1] >> 1) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0] >> 1) & 0x1) ? "闭合" : "未闭合"'
      - Name : "输出1"
        Value : '(($v[1]) & 0x1) ? "闭合" : "未闭合"'
        CValue : '((pData[0]) & 0x1) ? "闭合" : "未闭合"'
SET_RET_CODE : |
  case 100: {
      if(tab_reg[0] == last_data_) {
          cmd_result_ = 1;
      } else {
          cmd_result_ = 3;
      }
      Reset();
      return false;
    }
SET_AO_CODE: |
  if(setting["signal_id"].asString() == "100") {
      if(setting["SetValue"] != Json::nullValue && setting["SetValue"].type()  != Json::nullValue) {
          last_data_ = atoi(setting["SetValue"].asString().c_str());
          //DO输出
          state = 100;
          cmd_result_ = -1;
          OpenPort();
          modbus_write_register(7, last_data_);
          if((uint32_t)outBufferSize >= sizeof(int)) {
              *((int*)outBuffer) = 1;//通知取状态
              bytesReturned = sizeof(int);
          }                       
      }
  }