Project:
  Name : MS20
  RT_ID : 5156
  File : " MS20通讯协议Ver2.9"
Sample : 
  - Cmd : 4
    Offset : 1
    Len : 65
    Data : 
      - Name : "软件版本"
        Ratio : 100
        Offset : 1
      - Name : "当前电源电压"
        Ratio : 100
        Offset : 2
      - Name : "回风温度当前值"
        Ratio : 10
        Offset : 3
      - Name : "回风湿度当前值"
        Ratio : 10
        Offset : 4
      - Name : "回风：室外温度"
        Ratio : 10
        Offset : 5
      - Name : "回风：区域温度"
        Ratio : 10
        Offset : 6
      - Name : "回风：A路冷冻水进水温度"
        Ratio : 10
        Offset : 7
      - Name : "回风：A路冷冻水出水温度"
        Ratio : 10
        Offset : 8
      - Name : "回风：B路冷冻水进水温度"
        Ratio : 10
        Offset : 9
      - Name : "回风：B路冷冻水出水温度"
        Ratio : 10
        Offset : 10
      - Name : "回风：A路冷却水进水温度"
        Ratio : 10
        Offset : 11
      - Name : “回风：A路冷却水出水温度”
        Ratio : 10
        Offset : 12
      - Name : "回风：B路冷却水进水温度"
        Ratio : 10
        Offset : 13
      - Name : "回风：B路冷却水出水温度"
        Ratio : 10
        Offset : 14
      - Name : "回风：表冷器温度1"
        Ratio : 10
        Offset : 15
      - Name : "绝对湿度目标值"
        Ratio : 100
        Offset : 16
      - Name : "绝对湿度"
        Ratio : 100
        Offset : 17
      - Name : "主板NTC温度"
        Ratio : 10
        Offset : 18
      - Name : "送风温度当前值"
        Ratio : 10
        Offset : 19
      - Name : "送风湿度当前值"
        Ratio : 10
        Offset : 20
      - Name : "送风：NTC1_送风温度1"
        Ratio : 10
        Offset : 21
      - Name : "送风：NTC5_回风温度1"
        Ratio : 10
        Offset : 25
      - Name : "A路进水压力"
        Ratio : 100
        Offset : 33
      - Name : "A路出水压力/B路进水压力"
        Ratio : 100
        Offset : 34
      - Name : "冷冻水阀A开度反馈"
        Offset : 35
      - Name : "冷冻水阀B开度反馈"
        Offset : 36
      - Name : "AC本次启动运行时间（秒）"
        Offset : 37
      - Name : "风机运行累计时间"
        Unit : "时"
        Ratio : 2
        Offset : 39
      - Name : "1号压缩机运行累计时间"
        Unit : "时"
        Ratio : 2
        Offset : 42
      - Name : "1号压缩机吸气温度A"
        Ratio : 10
        Offset : 45
      - Name : "1号压缩机吸气温度B"
        Ratio : 10
        Offset : 46
      - Name : "1号压缩机排气温度"
        Ratio : 10
        Offset : 47
      - Name : "1号压缩机吸气压力"
        Ratio : 10
        Offset : 48
      - Name : "1号压缩机排气压力"
        Ratio : 10
        Offset : 49
      - Name : "2号压缩机运行累计时间"
        Unit : "时"
        Ratio : 2
        Offset : 50
      - Name : "2号压缩机吸气温度A"
        Ratio : 10
        Offset : 53
      - Name : "2号压缩机吸气温度B"
        Ratio : 10
        Offset : 54
      - Name : "2号压缩机排气温度"
        Ratio : 10
        Offset : 55
      - Name : "2号压缩机吸气压力"
        Ratio : 10
        Offset : 56
      - Name : "2号压缩机排气压力"
        Ratio : 10
        Offset : 57
      - Name : "3号压缩机运行累计时间"
        Unit : "时"
        Ratio : 2
        Offset : 58
      - Name : "3号压缩机吸气温度A"
        Ratio : 10
        Offset : 61
      - Name : "3号压缩机吸气温度B"
        Ratio : 10
        Offset : 62
      - Name : "3号压缩机排气温度"
        Ratio : 10
        Offset : 63
      - Name : "3号压缩机吸气压力"
        Ratio : 10
        Offset : 64
      - Name : "3号压缩机排气压力"
        Ratio : 10
        Offset : 65
  - Cmd : 4
    Offset : 136
    Len : 9
    Data : 
      - Name : "当前组合有功总电能"
        Value : (($v[2]<<16) + $v[1])
      - Name : "A相电压"
        Ratio : 10
        Offset : 3 
      - Name : "B相电压"
        Ratio : 10
        Offset : 4
      - Name : "C相电压"
        Ratio : 10
        Offset : 5
      - Name : "A相电流"
        Ratio : 100
        Offset : 3 
      - Name : "B相电流"
        Ratio : 100
        Offset : 4
      - Name : "C相电流"
        Ratio : 100
        Offset : 5
      - Name : "总有功功率"
        Value : (($v[9]<<16) + $v[8])