Project:
  Name : SchneiderDM2300
  RT_ID : 5156
  File : "DM23xx Register List Ver2.51.xlsx"
Sample : 
  - Cmd : 3
    Offset : 2700
    Len : 4
    RType : 'f'
    Data : 
      - Name : 有功电能输出
        Unit : kWh
      - Name : 有功电能输入
        Unit : kWh
  - Cmd : 3
    Offset : 2708
    Len : 4
    RType : 'f'
    Data : 
      - Name : 无功电能输出
        Unit : kVARh
      - Name : 无功电能输入
        Unit : kVARh
  - Cmd : 3
    Offset : 3000
    Len : 8
    RType : 'f'
    Data : 
      - Name : 电流A
        Unit : A
      - Name : 电流B
        Unit : A
      - Name : 电流C
        Unit : A
      - Name : 电流N
        Unit : A
  - Cmd : 3
    Offset : 3010
    Len : 4
    RType : 'f'
    Data : 
      - Name : 电流平均
        Unit : A
      - Name : 电流不平衡度
        Unit : '%'
  - Cmd : 3
    Offset : 3020
    Len : 14
    RType : 'f'
    Data : 
      - Name : AB线电压
        Unit : V
      - Name : BC线电压
        Unit : V
      - Name : CA线电压
        Unit : V
      - Name : 线电压平均值
        Unit : V
      - Name : A相电压
        Unit : V
      - Name : B相电压
        Unit : V
      - Name : C相电压
        Unit : V
  - Cmd : 3
    Offset : 3036
    Len : 4
    RType : 'f'
    Data : 
      - Name : 相电压平均值
        Unit : V
      - Name : 电压不平衡度
        Unit : V
  - Cmd : 3
    Offset : 3054
    Len : 32
    RType : 'f'
    Data : 
      - Name : A相有功功率
        Unit : kW
      - Name : B相有功功率
        Unit : kW
      - Name : C相有功功率
        Unit : kW
      - Name : 总有功功率
        Unit : kW
      - Name : A相无功功率
        Unit : kVAR
      - Name : B相无功功率
        Unit : kVAR
      - Name : C相无功功率
        Unit : kVAR
      - Name : 总无功功率
        Unit : kVAR
      - Name : A相视在功率
        Unit : kVA
      - Name : B相视在功率
        Unit : kVA
      - Name : C相视在功率
        Unit : kVA
      - Name : 总视在功率
        Unit : kVA
      - Name : A相功率因素
      - Name : B相功率因素
      - Name : C相功率因素
      - Name : 总功率因素
  - Cmd : 3
    Offset : 3110
    Len : 2
    RType : 'f'
    Data : 
      - Name : 频率
        Unit : Hz
