Project:
  Name : SL1882S_MZ3_5_2
  RT_ID : 5156
  File : "双模块热管空调室内机地址表.xls"
Sample : 
  - Cmd : 1
    Offset : 0
    Len : 54
    Data : 
      - Name : "进风温度故障"
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风湿度故障"
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#出风温度故障"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#出风温度故障"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "漏水报警"
        Offset : 13
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "电源故障报警"
        Offset : 14
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "滤网报警"
        Offset : 15
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#风机故障"
        Offset : 16
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#风机故障"
        Offset : 17
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风高湿报警"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风低湿报警"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风高温报警"
        Offset : 33
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风低温报警"
        Offset : 34
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "出风高温报警"
        Offset : 35
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "出风低温报警"
        Offset : 36
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "消防报警"
        Offset : 39
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#气管温度故障"
        Offset : 47
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#进风温度故障"
        Offset : 48
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#进风温度故障"
        Offset : 49
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#液管温度故障"
        Offset : 51
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#气管温度故障"
        Offset : 53
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#液管温度故障"
        Offset : 54
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
  - Cmd : 3
    Offset : 731
    Len : 1
    Data : 
      - Name : "温度设定/温差设定"
        Unit : "℃"
        Ratio : 10
  - Cmd : 3
    Offset : 76
    Len : 4
    Data : 
      - Name : "进风高湿报警设定"
        Ratio : 10
      - Name : "进风低湿报警设定"
        Ratio : 10
      - Name : "进风高温报警设定"
        Ratio : 10
      - Name : "进风低温报警设定"
        Ratio : 10
  - Cmd : 3
    Offset : 101
    Len : 4
    Data : 
      - Name : "出风高温报警设定"
        Ratio : 10
      - Name : "出风低温报警设定"
        Ratio : 10
  - Cmd : 1
    Offset : 176
    Len : 1
    Data : 
      - Name : "开关机"
        Options: 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
  - Cmd : 3
    Offset : 700
    Len : 6
    Data : 
      - Name : "进风温度"
        Ratio : 10
      - Name : "进风湿度"
        Ratio : 10
      - Name : "2#气管温度"
        Ratio : 10
      - Name : "2#液管温度"
        Ratio : 10
      - Name : "1#出风温度"
        Ratio : 10
      - Name : "2#出风温度"
        Ratio : 10
  - Cmd : 3
    Offset : 725
    Len : 3
    Data : 
      - Name : "1#气管温度"
        Ratio : 10
      - Name : "1#进风温度"
        Ratio : 10
      - Name : "2#进风温度"
        Ratio : 10
  - Cmd : 3
    Offset : 729
    Len : 1
    Data : 
      - Name : "1#液管温度"
        Ratio : 10
  - Cmd : 3
    Offset : 710
    Len : 2
    Data : 
      - Name : "1#风机转速"
        Unit : "RPM"
      - Name : "2#风机转速"
        Unit : "RPM"
  - Cmd : 3
    Offset : 770
    Len : 2
    Data : 
      - Name : "1#风机运行时间"
        Unit : "小时"
      - Name : "2#风机运行时间"
        Unit : "小时"
SET_RET_CODE : |
    case AC_Control_Code::AC_START:
    {
        cmd_result_ = 1;
        Reset();
        return false;
    }
      case AC_Control_Code::AC_STOP: {
        cmd_result_ = 1;
          Reset();
          return false;
      } 
      
SET_DO_CODE : |
  switch(b_mode_)
  {
      case 1://联通
      {
            //320是SET_DO
          std::string doId((char*)inBuffer, inBufferSize);
          if(doId == "601500201001" || doId == "140800280010") {
              //开机
              state = AC_Control_Code::AC_START;
              modbus_write_bit(176, 1);
              return 0;
          } else if(doId == "601500200001" || doId == "140800300010") {
              //关机
              state = AC_Control_Code::AC_STOP;
              modbus_write_bit(176, 0);
              return 0;
          }
          break;
      }
      case 2://电信
      {
          std::string doStr((char*)inBuffer, inBufferSize);
          Json::Value setting;//
          Json::Reader reader;//解析
          if(!reader.parse(doStr, setting)) {
            return -1;
          }
          if(setting.type() == Json::objectValue) {
              if(setting["signal_id"] != Json::nullValue && setting["signal_id"].type()  != Json::nullValue) {
                  if(setting["signal_id"].asString() != "") {
                      if(setting["signal_id"].asString() == "140800280010"){
                            //开机
                          state = AC_Control_Code::AC_START;
                          modbus_write_bit(176, 1);
                          return 0;
                      }else if(setting["signal_id"].asString() == "140800300010") {
                            //关机
                          state = AC_Control_Code::AC_STOP;
                          modbus_write_bit(176, 0);
                          return 0;
                      }
                  }
              }
          }
          break;
      }
  }
RunCheckThresholdCodeTelecom : |
    if(levelMap_["120800140010"]){
            CheckThresholdBool(levelMap_["120800140010"] , "120800140010", "120800140010", "精密空调溢水告警", "漏水报警",  cData.b1_0[12], 1);
    }
    if(levelMap_["110800540010"]){
            CheckThresholdBool(levelMap_["110800540010"] , "110800540010", "110800540010", "送风温度过高告警", "进风高温报警",  cData.b1_0[32], 1);
    }
    if(levelMap_["110800550010"]){
            CheckThresholdBool(levelMap_["110800550010"] , "110800550010", "110800550010", "送风温度过低告警", "进风低温报警",  cData.b1_0[33], 1);
    }
    if(levelMap_["120800120010"]){
            CheckThresholdBool(levelMap_["120800120010"] , "120800120010", "120800120010", "精密空调回风湿度高告警", "进风高湿报警",  cData.b1_0[30], 1);
    }
    if(levelMap_["120800260010"]){
            CheckThresholdBool(levelMap_["120800260010"] , "120800260010", "120800260010", "精密空调过滤网脏告警", "滤网报警",  cData.b1_0[14], 1);
    }
        