Project:
  Name : SL1882S_MZ3_5_2
  RT_ID : 5156
  File : "双模块热管空调室内机地址表.xls"
Sample : 
  - Cmd : 1
    Offset : 0
    Len : 54
    Data : 
      - Name : "进风温度故障"
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风湿度故障"
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#出风温度故障"
        Offset : 5
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#出风温度故障"
        Offset : 6
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "漏水报警"
        Offset : 13
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "电源故障报警"
        Offset : 14
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "滤网报警"
        Offset : 15
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#风机故障"
        Offset : 16
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#风机故障"
        Offset : 17
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风高湿报警"
        Offset : 31
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风低湿报警"
        Offset : 32
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风高温报警"
        Offset : 33
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "进风低温报警"
        Offset : 34
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "出风高温报警"
        Offset : 35
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "出风低温报警"
        Offset : 36
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "消防报警"
        Offset : 39
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#气管温度故障"
        Offset : 47
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#进风温度故障"
        Offset : 48
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#进风温度故障"
        Offset : 49
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "1#液管温度故障"
        Offset : 51
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#气管温度故障"
        Offset : 53
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
      - Name : "2#液管温度故障"
        Offset : 54
        AlertNormalValue : 0
        TeleSignalId : 12006
        TeleSignalName : SIGNAME_12006
  - Cmd : 3
    Offset : 731
    Len : 1
    Data : 
      - Name : "温度设定/温差设定"
        Unit : "℃"
        Ratio : 10
  - Cmd : 3
    Offset : 76
    Len : 4
    Data : 
      - Name : "进风高湿报警设定"
        Ratio : 10
      - Name : "进风低湿报警设定"
        Ratio : 10
      - Name : "进风高温报警设定"
        Ratio : 10
      - Name : "进风低温报警设定"
        Ratio : 10
  - Cmd : 3
    Offset : 101
    Len : 4
    Data : 
      - Name : "出风高温报警设定"
        Ratio : 10
      - Name : "出风低温报警设定"
        Ratio : 10
  - Cmd : 3
    Offset : 176
    Len : 1
    Data : 
      - Name : "开关机"
        Options: 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
  - Cmd : 3
    Offset : 700
    Len : 6
    Data : 
      - Name : "进风温度"
        Ratio : 10
      - Name : "进风湿度"
        Ratio : 10
      - Name : "2#气管温度"
        Ratio : 10
      - Name : "2#液管温度"
        Ratio : 10
      - Name : "1#出风温度"
        Ratio : 10
      - Name : "2#出风温度"
        Ratio : 10
  - Cmd : 3
    Offset : 725
    Len : 3
    Data : 
      - Name : "1#气管温度"
        Ratio : 10
      - Name : "1#进风温度"
        Ratio : 10
      - Name : "2#进风温度"
        Ratio : 10
  - Cmd : 3
    Offset : 729
    Len : 1
    Data : 
      - Name : "1#液管温度"
        Ratio : 10
  - Cmd : 3
    Offset : 710
    Len : 2
    Data : 
      - Name : "1#风机转速"
        Unit : "RPM"
      - Name : "2#风机转速"
        Unit : "RPM"
  - Cmd : 3
    Offset : 770
    Len : 2
    Data : 
      - Name : "1#风机运行时间"
        Unit : "小时"
      - Name : "2#风机运行时间"
        Unit : "小时"


        