Project:
  Name : ZXDCMeter
  RT_ID : 5156
  File : "直流显示屏通信协议(modbus rtu).docx"
BlockTemplate:
  Output:
    BlockLength : 18
    BlockType : 'S'
    BlockContent : 
      - Name : "%s组-序号"
      - Name : "%s组-开关规格"
      - Name : "%s组-电压"
        Unit : "V"
      - Name : "%s组-电流"
        Unit : "A"
      - Name : "%s组-负载率"
      - Name : "%s组-备用"
      - Name : "%s组-有功功率"
        Unit : "kW"
      - Name : "%s组-有功电度"
        Unit : "kWh"
      - Name : "%s组-开关状态"
        Options: 
          - Key : 0
            Value : "闭"
          - Key : 1
            Value : "开"
          - Key : 2
            Value : "未启用"
Sample :
  - Cmd : 3
    Offset : 7000
    Len : 12
    Data : 
      - Name : "输入I路开关规格"
      - Name : "输入I路电压"
        Ratio : 100
        Unit : "V"
      - Name : "输入I路电流"
        Ratio : 100
        Unit : "A"
      - Name : "输入I路负载率"
      - Name : "输入I路有功功率"
        Unit : "kw"
      - Name : "输入I路有功电度"
        Unit : "kwh"
      - Name : "输入II路开关规格"
      - Name : "输入II路电压"
        Ratio : 100
        Unit : "V"
      - Name : "输入II路电流"
        Ratio : 100
        Unit : "A"
      - Name : "输入II路负载率"
      - Name : "输入II路有功功率"
        Unit : "kw"
      - Name : "输入II路有功电度"
        Unit : "kwh"
  - Cmd : 3
    Offset : 7062
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 1
        ArrayEnd : 6
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7116
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 7
        ArrayEnd : 12
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7170
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 13
        ArrayEnd : 18
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7224
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 19
        ArrayEnd : 24
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7278
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 25
        ArrayEnd : 30
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7332
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 31
        ArrayEnd : 36
        Prefix : '输出I路'
  - Cmd : 3
    Offset : 7520
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 1
        ArrayEnd : 6
        Prefix : '输出II路'
  - Cmd : 3
    Offset : 7574
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 7
        ArrayEnd : 12
        Prefix : '输出II路'
  - Cmd : 3
    Offset : 7628
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 13
        ArrayEnd : 18
        Prefix : '输出II路'
  - Cmd : 3
    Offset : 7682
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 19
        ArrayEnd : 24
        Prefix : '输出II路'
  - Cmd : 3
    Offset : 7736
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 25
        ArrayEnd : 30
        Prefix : '输出II路'
  - Cmd : 3
    Offset : 7790
    Len : 54
    Data : 
      - ArrayBlock : Output
        ArrayStart : 31
        ArrayEnd : 36
        Prefix : '输出II路'
  